version: '3'
services:
    db:
      container_name: cms_db
      image: mongo
      restart: always
      ports:
        - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      volumes:
        - db_volume:/db/data
    cms_be:
      container_name: cms_be
      build:
        context: ./api
        dockerfile: Dockerfile
      restart: always
      volumes:
        - ./api:/api
      ports:
        - 8080:8080
      depends_on:
        - db
    cms_fe:
      container_name: cms_fe
      build:
        context: ./web
        dockerfile: Dockerfile
      restart: always
      volumes:
        - ./web/src:/src
      ports:
        - 3000:8090

volumes:
  db_volume: {}